image: atlassian/default-image:4

pipelines:
  branches:
    main:
      - step:
          name: Build, Tag, Push, and Deploy
          services:
            - docker
          caches:
            - docker
          script:
            - echo "🔧 Setting up variables"
            - export DATE_TAG=$(date +%d%m%y)
            - export ECR_REPO="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME"
            - export LOCAL_TAG="$IMAGE_NAME:$DATE_TAG"

            - echo "🔐 Logging into AWS ECR"
            - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

            - echo "🐳 Building Docker image: $LOCAL_TAG"
            - docker build -t $LOCAL_TAG .

            - echo "🏷 Tagging image as :latest and :$DATE_TAG"
            - docker tag $LOCAL_TAG $ECR_REPO:latest
            - docker tag $LOCAL_TAG $ECR_REPO:$DATE_TAG

            - echo "📦 Pushing to ECR"
            - docker push $ECR_REPO:latest
            - docker push $ECR_REPO:$DATE_TAG

            - echo "🚀 Updating ECS service"
            - aws ecs update-service \
                --cluster php-todo-cluster \
                --service php-todo-service \
                --force-new-deployment \
                --region $AWS_REGION
