version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html        # Mount app code into PHP container
    networks:
      - todo-net

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    container_name: nginx-todo
    ports:
      - "80:80"                    # Expose Nginx to host port 80
    depends_on:
      - php
    volumes:
      - ./app:/var/www/html        # Mount app code into Nginx container too
    networks:
      - todo-net

  redis:
    image: redis:7.2
    container_name: todo-redis
    ports:
      - "6379:6379"
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge
