services:
  php:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html
    networks:
      - todo-net

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    container_name: nginx-todo
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./app:/var/www/html
    networks:
      - todo-net

  redis-slave:
    image: redis:7.2
    container_name: todo-redis-slave
    command: [
      "redis-server",
      "--replicaof", "172.31.14.14", "6379",
      "--masterauth", "123456"
    ]
    ports:
      - "6380:6379" # Expose slave on host port 6380
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge
