version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html
    networks:
      - todo-net

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    container_name: nginx-todo
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - todo-net

  redis:
    image: redis:7.2
    container_name: todo-redis
    ports:
      - "6379:6379"
    networks:
      - todo-net

networks:
  todo-net:
